In [4]:
from data_transform import load_array_from_dir, load_ann_from_dir

In [5]:
WINDOW_SIZE = 60*300
trainset = load_array_from_dir("./data/training2017/", WINDOW_SIZE)

100%|██████████| 8528/8528 [00:02<00:00, 3315.40it/s]


In [6]:
trainset.shape

(8528, 18000)

In [8]:
traintarget = load_ann_from_dir("./data/training2017/")

In [9]:
print(len(traintarget))

8528


In [10]:
import scipy

In [11]:
scipy.io.savemat('trainingset.mat', mdict={'trainset': trainset, 'traintarget': traintarget})

In [12]:
from the_main import loaddata

In [13]:
(X_train, y_train) = loaddata(WINDOW_SIZE)

Loading data training set


In [15]:
import numpy as np

In [17]:
X_train.shape

(8528, 18000)

In [16]:
batch = 64
epochs = 20
rep = 1         # K fold procedure can be repeated multiple times
Kfold = 5
Ntrain = 8528 # number of recordings on training set
Nsamp = int(Ntrain/Kfold) # number of recordings to take as validation

In [19]:

# Need to add dimension for training
X_train = np.expand_dims(X_train, axis=2)
classes = ['A', 'N', 'O', '~']
Nclass = len(classes)
cvconfusion = np.zeros((Nclass, Nclass, Kfold*rep))
cvscores = []

In [23]:
X = X_train

In [24]:
idxval = np.random.choice(Ntrain, Nsamp, replace=False)
idxtrain = np.invert(np.in1d(range(X.shape[0]), idxval))

In [25]:
idxval

array([8506, 7455, 5480, ..., 1322, 4847, 3199])

In [26]:
np.in1d(range(X.shape[0]), idxval)

array([False, False,  True, ..., False, False, False])

In [27]:
idxtrain

array([ True,  True, False, ...,  True,  True,  True])